---
apiVersion: v1
kind: Namespace
metadata:
  name: boinc
# I set up a ResourceQuota for my "boinc" namespace just to learn how to do it.
# You can delete this and the request and limits in the deployment if you don't need them.
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: boinclimits
  namespace: boinc
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boinc-config
  namespace: boinc
data:
  # You can change the timezone of your Boinc client to your local timezone.  Use the examples in
  # /usr/share/zoneinfo.
  timezone: "America/Chicago"
  boinc_opts: "--allow_remote_gui_rpc"
---
apiVersion: v1
kind: Secret
metadata:
  name: boinc-secret
  namespace: boinc
data:
  # Base64-encode the password.  To do this, run the command:
  # echo -n 'mypass' | base64
  # Paste the output, replacing "<PASSWORD" in the next line
  rpc_password: <PASSWORD>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: boincdata
  namespace: boinc
  labels:
    volume: boinc
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  # I used a NFS share on my home network as the persistent storage volume for Boinc to use.
  # Replace it with your own volume definition.
  nfs:
    server: homeserver.local
    path: "/nfsshare/boinc"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: boincdata
  namespace: boinc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: Service
metadata:
  name: boinc
  namespace: boinc
spec:
  selector:
    app: boinc
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
      # I set the port up as a NodePort, using the default port.  This makes the Boinc client
      # accessible from either the master or any of the Kerberos nodes on port 31416
    - port: 31416
      name: manager
      protocol: TCP
      nodePort: 31416
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boinc
  namespace: boinc
  labels:
    app: boinc
spec:
  replicas: 1
  template:
    metadata:
      name: boinc
      namespace: boinc
      labels:
        app: boinc
    spec:
      containers:
        - name: boinc
          image: boinc/client
          imagePullPolicy: Always
# If you don't need resource limits, you can delete these and the ResourceQuota at the top.
          resources:
            requests:
              memory: 3Gi
              cpu: 3
            limits:
              memory: 3Gi
              cpu: 3
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: boinc-config
                  key: timezone
            - name: BOINC_CMD_LINE_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: boinc-config
                  key: boinc_opts
            - name: BOINC_GUI_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: rpc_password
          volumeMounts:
            - mountPath: /var/lib/boinc
              name: boincdata
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
      volumes:
        - name: boincdata
          persistentVolumeClaim:
            claimName: boincdata
  selector:
    matchLabels:
      app: boinc
